version: '3.4'
services:
  callprice-api:
    container_name: callprice-api
    build:
      context: callprice-api
      dockerfile: callprice-api.Dockerfile
    ports:
      - "8081:8081"

  callprice-front:
    container_name: callprice-front
    build:
      context: callprice-front
      dockerfile: callprice-front.Dockerfile
    ports:
      - "8080:80"